package candlestickGranularity

import "gitlab.com/personal/go/gOanda/V20"

const S5 V20.CandlestickGranularity = "S5"
const S10 V20.CandlestickGranularity = "S10"
const S15 V20.CandlestickGranularity = "S15"
const S30 V20.CandlestickGranularity = "S30"
const M1 V20.CandlestickGranularity = "M1"
const M2 V20.CandlestickGranularity = "M2"
const M4 V20.CandlestickGranularity = "M4"
const M5 V20.CandlestickGranularity = "M5"
const M10 V20.CandlestickGranularity = "M10"
const M15 V20.CandlestickGranularity = "M15"
const M30 V20.CandlestickGranularity = "M30"
const H1 V20.CandlestickGranularity = "H1"
const H2 V20.CandlestickGranularity = "H2"
const H3 V20.CandlestickGranularity = "H3"
const H4 V20.CandlestickGranularity = "H4"
const H6 V20.CandlestickGranularity = "H6"
const H8 V20.CandlestickGranularity = "H8"
const H12 V20.CandlestickGranularity = "H12"
const D V20.CandlestickGranularity = "D"
const W V20.CandlestickGranularity = "W"
const M V20.CandlestickGranularity = "M"
