package gOanda

const INSTRUMENT_TYPE_CURRENCY = "CURRENCY"
const INSTRUMENT_TYPE_CFD = "CFD"
const INSTRUMENT_TYPE_METAL = "METAL"

const ACCEPT_DATETIME_FORMAT_UNIX = "UNIX"
const ACCEPT_DATETIME_FORMAT_RFC3339 = "RFC3999"

const DIRECTION_LONG = "LONG"
const DIRECTION_SHORT = "SHORT"

const GUARANTEED_STOP_LOSS_ORDER_MODE_DISABLED = "DISABLED"
const GUARANTEED_STOP_LOSS_ORDER_MODE_ALLOWED = "ALLOWED"
const GUARANTEED_STOP_LOSS_ORDER_MODE_REQUIRED = "REQUIRED"

const ACCOUNT_FINANCING_MODE_NO_FINANCING = "NO_FINANCING"
const ACCOUNT_FINANCING_MODE_SECOND_BY_SECOND = "SECOND_BY_SECOND"
const ACCOUNT_FINANCING_MODE_DAILY = "DAILY"

const POSITION_AGGREGATION_MODE_ABSOLUTE_SUM = "ABSOLUTE_SUM"
const POSITION_AGGREGATION_MODE_MAXIMAL_SIDE = "MAXIMAL_SIDE"
const POSITION_AGGREGATION_MODE_NET_SUM = "NET_SUM"
